package ir.am3n.rtsp.client.data

import ir.am3n.rtsp.client.interfaces.Frame
import ir.am3n.utils.VideoCodecType

data class VideoFrame(
    /** Only H264 codec supported */
    val codecType: VideoCodecType,
    /** Indicates whether it is a keyframe or not */
    val isKeyframe: Boolean,
    override val data: ByteArray,
    override val offset: Int,
    override val length: Int,
    /** Video frame timestamp (millis) generated by camera */
    override val timestamp: Long,
    /** Captured (received) video frame timestamp (millis). If -1, not supported. */
    val capturedTimestamp: Long = -1
) : Frame {

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as VideoFrame

        if (codecType != other.codecType) return false
        if (isKeyframe != other.isKeyframe) return false
        if (!data.contentEquals(other.data)) return false
        if (offset != other.offset) return false
        if (length != other.length) return false
        if (timestamp != other.timestamp) return false
        if (capturedTimestamp != other.capturedTimestamp) return false

        return true
    }

    override fun hashCode(): Int {
        var result = codecType.hashCode()
        result = 31 * result + isKeyframe.hashCode()
        result = 31 * result + data.contentHashCode()
        result = 31 * result + offset
        result = 31 * result + length
        result = 31 * result + timestamp.hashCode()
        result = 31 * result + capturedTimestamp.hashCode()
        return result
    }

}
